### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by Hombre2014** [Kliton/react-kanban-board-dnd-kit-tutorial-yt#7]
I can not say when exactly this bug happens, but I have experienced it quite often.
Normally when you load the app for the first time and try to move a task from the "Work in Progress" column to the "ToDo" column, although I am putting the task on the very top of the list, so the overlay shows that it is going to be the very first task in this column, once I dropped the tasks, it goes at the very bottom of the column.

**Comment by cyonder** [comment]
Came here to open the same issue. It can be produced on the Author's live app too! @Kliton 

![CleanShot 2024-03-09 at 20 09 50](https://github.com/Kliton/react-kanban-board-dnd-kit-tutorial-yt/assets/10395746/6d3ff0e7-4561-4f34-b929-648d76a8bec7)

https://react-kanban-board-dnd-kit-tutorial-yt.vercel.app

**Comment by mnofrizal** [comment]
any update on this ?

**Comment by Hombre2014** [comment]
It seems that the repo is not maintained.

**Comment by atumas-bananamilk** [comment]
Had the same issue, with tasks randomly dropping to the top / bottom of another column.
Fixed it like this:

![Screenshot 2024-05-02 at 17 45 49](https://github.com/Kliton/react-kanban-board-dnd-kit-tutorial-yt/assets/22228431/ab0a42ed-5e3f-47d1-962e-c05b88b37359)

**Comment by atumas-bananamilk** [comment]
Had the same issue, with tasks randomly dropping to the top / bottom of another column.
Fixed it like this:

![Screenshot 2024-05-02 at 17 45 49](https://github.com/Kliton/react-kanban-board-dnd-kit-tutorial-yt/assets/22228431/ab0a42ed-5e3f-47d1-962e-c05b88b37359)

**Comment by AimeurAmin** [comment]
I see a PR was merged as a fix to this issue, yet the issue persists
